site_name: LightRL Documentation
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Examples: examples.md
  - API Documentation: api.md

theme:
  name: material
  features:
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: True
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Optional: You can specify the directory where the documentation source files are located.
docs_dir: docs
# site_dir: site