site_name: LightRL Documentation
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Exmaples: examples.md
  - API Documentation: api.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: True

# Optional: You can specify the directory where the documentation source files are located.
docs_dir: docs
# site_dir: site