name: Publish to PyPI

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi

    steps:
    - name: Check if both branch and tag conditions are satisfied
      run: |
        if [[ "$GITHUB_REF" != refs/tags/v* ]] || [[ "$GITHUB_BASE_REF" != main ]]; then
          echo "Conditions not satisfied, exiting."
          exit 1
        fi
        
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*