name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'   # This triggers workflow on tags matching vX.X.X format

jobs:
  build-and-publish:
    if: github.ref == 'refs/heads/main' && startsWith(github.event.ref, 'refs/tags/v') # Ensure it's main and a version tag
    runs-on: ubuntu-latest
    environment: pypi

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*